name: Integration-test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-qemu-action@v2

      - name: Make wait-for-it.sh executable
        uses: chmod +x ./integration-test/scripts/run-integration.sh

      - name: copy env.example to .env
        run: cp ./integration-test/env.example ./integration-test/.env

      - name: run the script
        run: cd integration-test && npm run test:integration
